package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppAcesso generated by hbm2java
 */

@SuppressWarnings("serial")
@Entity
@Table(name = "app_acesso")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppAcesso implements java.io.Serializable{

	private int ascId;
	private AppUsuario appUsuario;
	private String nome;
	private String login;
	private String senha;
	private String chave;

	public AppAcesso() {
	}

	public AppAcesso(int ascId, AppUsuario appUsuario, String nome,
			String login, String senha) {
		this.ascId = ascId;
		this.appUsuario = appUsuario;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
	}

	public AppAcesso(int ascId, AppUsuario appUsuario, String nome,
			String login, String senha, String chave) {
		this.ascId = ascId;
		this.appUsuario = appUsuario;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
		this.chave = chave;
	}

	@Id
	@Column(name = "asc_id", unique = true, nullable = false)
	public int getAscId() {
		return this.ascId;
	}

	public void setAscId(int ascId) {
		this.ascId = ascId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usr_id", nullable = false)
	public AppUsuario getAppUsuario() {
		return this.appUsuario;
	}

	public void setAppUsuario(AppUsuario appUsuario) {
		this.appUsuario = appUsuario;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "login", nullable = false, length = 100)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", nullable = false)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "chave")
	public String getChave() {
		return this.chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

}
