package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppDocumentoDigital generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_documento_digital")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppDocumentoDigital implements java.io.Serializable{

	private int ddgId;
	private AppTabela appTabela;
	private String nome;
	private String fonteDado;
	private String tipo;

	public AppDocumentoDigital() {
	}

	public AppDocumentoDigital(int ddgId, AppTabela appTabela) {
		this.ddgId = ddgId;
		this.appTabela = appTabela;
	}

	public AppDocumentoDigital(int ddgId, AppTabela appTabela, String nome,
			String fonteDado, String tipo) {
		this.ddgId = ddgId;
		this.appTabela = appTabela;
		this.nome = nome;
		this.fonteDado = fonteDado;
		this.tipo = tipo;
	}

	@Id
	@Column(name = "ddg_id", unique = true, nullable = false)
	public int getDdgId() {
		return this.ddgId;
	}

	public void setDdgId(int ddgId) {
		this.ddgId = ddgId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tbl_id", nullable = false)
	public AppTabela getAppTabela() {
		return this.appTabela;
	}

	public void setAppTabela(AppTabela appTabela) {
		this.appTabela = appTabela;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "fonte_dado")
	public String getFonteDado() {
		return this.fonteDado;
	}

	public void setFonteDado(String fonteDado) {
		this.fonteDado = fonteDado;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
