package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppDicionarioDado generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_dicionario_dado")
public class AppDicionarioDado implements java.io.Serializable {

	private int ddId;
	private AppPermissao appPermissao;
	private AppTabela appTabela;
	private String atributo;
	private Boolean readOnly;
	private Boolean writeOnly;
	private Boolean readWrite;

	public AppDicionarioDado() {
	}

	public AppDicionarioDado(int ddId, AppPermissao appPermissao,
			AppTabela appTabela) {
		this.ddId = ddId;
		this.appPermissao = appPermissao;
		this.appTabela = appTabela;
	}

	public AppDicionarioDado(int ddId, AppPermissao appPermissao,
			AppTabela appTabela, String atributo, Boolean readOnly,
			Boolean writeOnly, Boolean readWrite) {
		this.ddId = ddId;
		this.appPermissao = appPermissao;
		this.appTabela = appTabela;
		this.atributo = atributo;
		this.readOnly = readOnly;
		this.writeOnly = writeOnly;
		this.readWrite = readWrite;
	}

	@Id
	@Column(name = "dd_id", unique = true, nullable = false)
	public int getDdId() {
		return this.ddId;
	}

	public void setDdId(int ddId) {
		this.ddId = ddId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pem_id", nullable = false)
	public AppPermissao getAppPermissao() {
		return this.appPermissao;
	}

	public void setAppPermissao(AppPermissao appPermissao) {
		this.appPermissao = appPermissao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_id", nullable = false)
	public AppTabela getAppTabela() {
		return this.appTabela;
	}

	public void setAppTabela(AppTabela appTabela) {
		this.appTabela = appTabela;
	}

	@Column(name = "atributo")
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	@Column(name = "read_only")
	public Boolean getReadOnly() {
		return this.readOnly;
	}

	public void setReadOnly(Boolean readOnly) {
		this.readOnly = readOnly;
	}

	@Column(name = "write_only")
	public Boolean getWriteOnly() {
		return this.writeOnly;
	}

	public void setWriteOnly(Boolean writeOnly) {
		this.writeOnly = writeOnly;
	}

	@Column(name = "read_write")
	public Boolean getReadWrite() {
		return this.readWrite;
	}

	public void setReadWrite(Boolean readWrite) {
		this.readWrite = readWrite;
	}

}
