package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppDicionarioDado generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_dicionario_dado")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppDicionarioDado implements Serializable{

	private int ddId;
	private AppPermissao appPermissao;
	private AppTabela appTabela;
	private String atributo;
	private boolean pesquisa;
	

	public AppDicionarioDado() {
	}

	public AppDicionarioDado(int ddId, AppPermissao appPermissao,
			AppTabela appTabela) {
		this.ddId = ddId;
		this.appPermissao = appPermissao;
		this.appTabela = appTabela;
	}

	public AppDicionarioDado(int ddId, AppPermissao appPermissao,
			AppTabela appTabela, String atributo,Boolean pesquisa) {
		this.ddId = ddId;
		this.appPermissao = appPermissao;
		this.appTabela = appTabela;
		this.atributo = atributo;
		this.pesquisa = pesquisa;
		
	}

	@Id
	@Column(name = "dd_id", unique = true, nullable = false)
	public int getDdId() {
		return this.ddId;
	}

	public void setDdId(int ddId) {
		this.ddId = ddId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pem_id", nullable = false)
	public AppPermissao getAppPermissao() {
		return this.appPermissao;
	}

	public void setAppPermissao(AppPermissao appPermissao) {
		this.appPermissao = appPermissao;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tbl_id", nullable = false)
	public AppTabela getAppTabela() {
		return this.appTabela;
	}

	public void setAppTabela(AppTabela appTabela) {
		this.appTabela = appTabela;
	}

	@Column(name = "atributo")
	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}
	
	@Column(name = "pesquisa")
	public boolean isPesquisa() {
		return pesquisa;
	}

	public void setPesquisa(boolean pesquisa) {
		this.pesquisa = pesquisa;
	}


}
