package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppEndereco generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_endereco")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppEndereco implements java.io.Serializable{

	private int endId;
	private AppUsuario appUsuario;
	private String logradouro;
	private String numero;
	private String complemento;
	private String cep;
	private String bairro;
	private String cidade;
	private String uf;

	public AppEndereco() {
	}

	public AppEndereco(int endId, AppUsuario appUsuario) {
		this.endId = endId;
		this.appUsuario = appUsuario;
	}

	public AppEndereco(int endId, AppUsuario appUsuario, String logradouro,
			String numero, String complemento, String cep, String bairro,
			String cidade, String uf) {
		this.endId = endId;
		this.appUsuario = appUsuario;
		this.logradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
		this.cep = cep;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
	}

	@Id
	@Column(name = "end_id", unique = true, nullable = false)
	public int getEndId() {
		return this.endId;
	}

	public void setEndId(int endId) {
		this.endId = endId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usr_id", nullable = false)
	public AppUsuario getAppUsuario() {
		return this.appUsuario;
	}

	public void setAppUsuario(AppUsuario appUsuario) {
		this.appUsuario = appUsuario;
	}

	@Column(name = "logradouro")
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero", length = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 50)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "cep", length = 9)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "bairro", length = 150)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade")
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "uf", length = 10)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

}
