package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppFuncao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_funcao", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppFuncao implements Serializable{

	private int funId;
	private AppPerfil appPerfil;
	private int codigo;
	private String nome;
	private String descricao;

	public AppFuncao() {
	}

	public AppFuncao(int funId, AppPerfil appPerfil, int codigo) {
		this.funId = funId;
		this.appPerfil = appPerfil;
		this.codigo = codigo;
	}

	public AppFuncao(int funId, AppPerfil appPerfil, int codigo, String nome,
			String descricao) {
		this.funId = funId;
		this.appPerfil = appPerfil;
		this.codigo = codigo;
		this.nome = nome;
		this.descricao = descricao;
	}

	@Id
	@Column(name = "fun_id", unique = true, nullable = false)
	public int getFunId() {
		return this.funId;
	}

	public void setFunId(int funId) {
		this.funId = funId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "prf_id", nullable = false)
	public AppPerfil getAppPerfil() {
		return this.appPerfil;
	}

	public void setAppPerfil(AppPerfil appPerfil) {
		this.appPerfil = appPerfil;
	}

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
