package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppPerfil generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_perfil")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AppPerfil implements java.io.Serializable{

	private int prfId;
	private String perfil;
	private Set<AppFuncao> appFuncaos = new HashSet<AppFuncao>(0);
	private Set<AppTema> appTemas = new HashSet<AppTema>(0);
	private Set<AppUsarioxprefil> appUsarioxprefils = new HashSet<AppUsarioxprefil>(0);

	public AppPerfil() {
	}

	public AppPerfil(int prfId) {
		this.prfId = prfId;
	}

	public AppPerfil(int prfId, String perfil, Set<AppFuncao> appFuncaos, Set<AppTema> appTemas,
			Set<AppUsarioxprefil> appUsarioxprefils) {
		this.prfId = prfId;
		this.perfil = perfil;
		this.appFuncaos = appFuncaos;
		this.appTemas = appTemas;
		this.appUsarioxprefils = appUsarioxprefils;
	}

	@Id
	@Column(name = "prf_id", unique = true, nullable = false)
	public int getPrfId() {
		return this.prfId;
	}

	public void setPrfId(int prfId) {
		this.prfId = prfId;
	}

	@Column(name = "perfil")
	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "appPerfil")
	public Set<AppFuncao> getAppFuncaos() {
		return this.appFuncaos;
	}

	public void setAppFuncaos(Set<AppFuncao> appFuncaos) {
		this.appFuncaos = appFuncaos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "appPerfil")
	public Set<AppTema> getAppTemas() {
		return this.appTemas;
	}

	public void setAppTemas(Set<AppTema> appTemas) {
		this.appTemas = appTemas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "appPerfil")
	public Set<AppUsarioxprefil> getAppUsarioxprefils() {
		return this.appUsarioxprefils;
	}

	public void setAppUsarioxprefils(Set<AppUsarioxprefil> appUsarioxprefils) {
		this.appUsarioxprefils = appUsarioxprefils;
	}

}
