package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * AppPermissao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "app_permissao")
@JsonIgnoreProperties({ "internal" })
public class AppPermissao implements java.io.Serializable{

	private int pemId;
	private AppTema appTema;
	private Integer resume;
	private String permit;
	private Set<AppDicionarioDado> appDicionarioDados = new HashSet<AppDicionarioDado>(0);
	public AppPermissao() {
	}

	public AppPermissao(int pemId, AppTema appTema) {
		this.pemId = pemId;
		this.appTema = appTema;
	}

	public AppPermissao(int pemId, AppTema appTema, Boolean queried,
			Integer resume, String permit, Set<AppDicionarioDado> appDicionarioDados) {
		this.pemId = pemId;
		this.appTema = appTema;
		this.resume = resume;
		this.permit = permit;
		this.appDicionarioDados = appDicionarioDados;
	}

	@Id
	@Column(name = "pem_id", unique = true, nullable = false)
	public int getPemId() {
		return this.pemId;
	}

	public void setPemId(int pemId) {
		this.pemId = pemId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tma_id", nullable = false)
	public AppTema getAppTema() {
		return this.appTema;
	}

	public void setAppTema(AppTema appTema) {
		this.appTema = appTema;
	}

	@Column(name = "resume")
	public Integer getResume() {
		return this.resume;
	}

	public void setResume(Integer resume) {
		this.resume = resume;
	}

	@Column(name = "permit")
	public String getPermit() {
		return this.permit;
	}

	public void setPermit(String permit) {
		this.permit = permit;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "appPermissao")
	public Set<AppDicionarioDado> getAppDicionarioDados() {
		return this.appDicionarioDados;
	}

	public void setAppDicionarioDados(Set<AppDicionarioDado> appDicionarioDados) {
		this.appDicionarioDados = appDicionarioDados;
	}

}
