package geopixel.model.hb.dto;

// default package
// Generated 15/07/2015 12:59:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppUsarioxprefilId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable

public class AppUsarioxprefilId implements java.io.Serializable {

	private int prfId;
	private int usrId;

	public AppUsarioxprefilId() {
	}

	public AppUsarioxprefilId(int prfId, int usrId) {
		this.prfId = prfId;
		this.usrId = usrId;
	}

	@Column(name = "prf_id", nullable = false)
	public int getPrfId() {
		return this.prfId;
	}

	public void setPrfId(int prfId) {
		this.prfId = prfId;
	}

	@Column(name = "usr_id", nullable = false)
	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppUsarioxprefilId))
			return false;
		AppUsarioxprefilId castOther = (AppUsarioxprefilId) other;

		return (this.getPrfId() == castOther.getPrfId())
				&& (this.getUsrId() == castOther.getUsrId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrfId();
		result = 37 * result + this.getUsrId();
		return result;
	}

}
