package geopixel.model.legacy.dto;

import java.io.Serializable;

/**
 * Model class of app_acesso.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Acesso implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** asc_id. */
	private Integer ascId;

	/** login. */
	private String login;

	/** senha. */
	private String senha;

	/** nome. */
	private String nome;

	/** key. */
	private String chave;
	
	/** app_usuario. */
	private Usuario Usuario;

	/**
	 * Constructor.
	 */
	public Acesso() {
	}

	/**
	 * Set the asc_id.
	 * 
	 * @param ascId
	 *            asc_id
	 */
	public void setAscId(Integer ascId) {
		this.ascId = ascId;
	}

	/**
	 * Get the asc_id.
	 * 
	 * @return asc_id
	 */
	public Integer getAscId() {
		return this.ascId;
	}

	/**
	 * Set the login.
	 * 
	 * @param login
	 *            login
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * Get the login.
	 * 
	 * @return login
	 */
	public String getLogin() {
		return this.login;
	}

	/**
	 * Set the senha.
	 * 
	 * @param senha
	 *            senha
	 */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/**
	 * Get the senha.
	 * 
	 * @return senha
	 */
	public String getSenha() {
		return this.senha;
	}

	/**
	 * Set the appkey.
	 * 
	 * @param appkey
	 *            appkey
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * Get the appkey.
	 * 
	 * @return appkey
	 */
	public String getNome() {
		return this.nome;
	}
	
	

	public String getChave() {
		return chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	/**
	 * Set the app_usuario.
	 * 
	 * @param appUsuario
	 *            app_usuario
	 */
	public void setUsuario(Usuario usuario) {
		this.Usuario = usuario;
	}

	/**
	 * Get the app_usuario.
	 * 
	 * @return app_usuario
	 */
	public Usuario getUsuario() {
		return this.Usuario;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ascId == null) ? 0 : ascId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Acesso other = (Acesso) obj;
		if (ascId == null) {
			if (other.ascId != null) {
				return false;
			}
		} else if (!ascId.equals(other.ascId)) {
			return false;
		}
		return true;
	}

}
