package geopixel.model.legacy.dto;

import java.io.Serializable;

/**
 * Model class of app_dicionario_dado.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DicionarioDado implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** dd_id. */
	private Integer ddId;

	/** atributo. */
	private String atributo;

	/** read_only. */
	private Boolean readOnly;

	/** write_only. */
	private Boolean writeOnly;

	/** read_write. */
	private Boolean readWrite;

	/** app_tabela. */
	private Tabela appTabela;

	/** app_permissao. */
	private Permissao appPermissao;

	/**
	 * Constructor.
	 */
	public DicionarioDado() {
	}

	/**
	 * Set the dd_id.
	 * 
	 * @param ddId
	 *            dd_id
	 */
	public void setDdId(Integer ddId) {
		this.ddId = ddId;
	}

	/**
	 * Get the dd_id.
	 * 
	 * @return dd_id
	 */
	public Integer getDdId() {
		return this.ddId;
	}

	/**
	 * Set the atributo.
	 * 
	 * @param atributo
	 *            atributo
	 */
	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	/**
	 * Get the atributo.
	 * 
	 * @return atributo
	 */
	public String getAtributo() {
		return this.atributo;
	}

	/**
	 * Set the read_only.
	 * 
	 * @param readOnly
	 *            read_only
	 */
	public void setReadOnly(Boolean readOnly) {
		this.readOnly = readOnly;
	}

	/**
	 * Get the read_only.
	 * 
	 * @return read_only
	 */
	public Boolean getReadOnly() {
		return this.readOnly;
	}

	/**
	 * Set the write_only.
	 * 
	 * @param writeOnly
	 *            write_only
	 */
	public void setWriteOnly(Boolean writeOnly) {
		this.writeOnly = writeOnly;
	}

	/**
	 * Get the write_only.
	 * 
	 * @return write_only
	 */
	public Boolean getWriteOnly() {
		return this.writeOnly;
	}

	/**
	 * Set the read_write.
	 * 
	 * @param readWrite
	 *            read_write
	 */
	public void setReadWrite(Boolean readWrite) {
		this.readWrite = readWrite;
	}

	/**
	 * Get the read_write.
	 * 
	 * @return read_write
	 */
	public Boolean getReadWrite() {
		return this.readWrite;
	}

	/**
	 * Set the app_tabela.
	 * 
	 * @param appTabela
	 *            app_tabela
	 */
	public void setAppTabela(Tabela appTabela) {
		this.appTabela = appTabela;
	}

	/**
	 * Get the app_tabela.
	 * 
	 * @return app_tabela
	 */
	public Tabela getAppTabela() {
		return this.appTabela;
	}

	/**
	 * Set the app_permissao.
	 * 
	 * @param appPermissao
	 *            app_permissao
	 */
	public void setAppPermissao(Permissao appPermissao) {
		this.appPermissao = appPermissao;
	}

	/**
	 * Get the app_permissao.
	 * 
	 * @return app_permissao
	 */
	public Permissao getAppPermissao() {
		return this.appPermissao;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ddId == null) ? 0 : ddId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DicionarioDado other = (DicionarioDado) obj;
		if (ddId == null) {
			if (other.ddId != null) {
				return false;
			}
		} else if (!ddId.equals(other.ddId)) {
			return false;
		}
		return true;
	}

}
