package geopixel.model.legacy.dto;

import java.io.Serializable;

/**
 * Model class of app_documento_digital.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DocumentoDigital implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ddg_id. */
	private Integer ddgId;

	/** nome. */
	private String nome;

	/** fonte_dado. */
	private String fonteDado;

	/** tipo. */
	private String tipo;

	/** app_tabela. */
	private Tabela appTabela;

	/**
	 * Constructor.
	 */
	public DocumentoDigital() {
	}

	/**
	 * Set the ddg_id.
	 * 
	 * @param ddgId
	 *            ddg_id
	 */
	public void setDdgId(Integer ddgId) {
		this.ddgId = ddgId;
	}

	/**
	 * Get the ddg_id.
	 * 
	 * @return ddg_id
	 */
	public Integer getDdgId() {
		return this.ddgId;
	}

	/**
	 * Set the nome.
	 * 
	 * @param nome
	 *            nome
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * Get the nome.
	 * 
	 * @return nome
	 */
	public String getNome() {
		return this.nome;
	}

	/**
	 * Set the fonte_dado.
	 * 
	 * @param fonteDado
	 *            fonte_dado
	 */
	public void setFonteDado(String fonteDado) {
		this.fonteDado = fonteDado;
	}

	/**
	 * Get the fonte_dado.
	 * 
	 * @return fonte_dado
	 */
	public String getFonteDado() {
		return this.fonteDado;
	}

	/**
	 * Set the tipo.
	 * 
	 * @param tipo
	 *            tipo
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * Get the tipo.
	 * 
	 * @return tipo
	 */
	public String getTipo() {
		return this.tipo;
	}

	/**
	 * Set the app_tabela.
	 * 
	 * @param appTabela
	 *            app_tabela
	 */
	public void setAppTabela(Tabela appTabela) {
		this.appTabela = appTabela;
	}

	/**
	 * Get the app_tabela.
	 * 
	 * @return app_tabela
	 */
	public Tabela getAppTabela() {
		return this.appTabela;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ddgId == null) ? 0 : ddgId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DocumentoDigital other = (DocumentoDigital) obj;
		if (ddgId == null) {
			if (other.ddgId != null) {
				return false;
			}
		} else if (!ddgId.equals(other.ddgId)) {
			return false;
		}
		return true;
	}

}
