package geopixel.model.legacy.dto;

import java.io.Serializable;

/**
 * Model class of app_funcao.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Funcao implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** fun_id. */
	private Integer funId;

	/** codigo. */
	private Integer codigo;

	/** nome . */
	private String nome ;

	/** descricao. */
	private String descricao;

	/** app_perfil. */
	private Perfil appPerfil;

	/**
	 * Constructor.
	 */
	public Funcao() {
	}

	/**
	 * Set the fun_id.
	 * 
	 * @param funId
	 *            fun_id
	 */
	public void setFunId(Integer funId) {
		this.funId = funId;
	}

	/**
	 * Get the fun_id.
	 * 
	 * @return fun_id
	 */
	public Integer getFunId() {
		return this.funId;
	}

	/**
	 * Set the codigo.
	 * 
	 * @param codigo
	 *            codigo
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * Get the codigo.
	 * 
	 * @return codigo
	 */
	public Integer getCodigo() {
		return this.codigo;
	}

	/**
	 * Set the nome .
	 * 
	 * @param nome 
	 *            nome 
	 */
	public void setNome (String nome ) {
		this.nome  = nome ;
	}

	/**
	 * Get the nome .
	 * 
	 * @return nome 
	 */
	public String getNome () {
		return this.nome ;
	}

	/**
	 * Set the descricao.
	 * 
	 * @param descricao
	 *            descricao
	 */
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	/**
	 * Get the descricao.
	 * 
	 * @return descricao
	 */
	public String getDescricao() {
		return this.descricao;
	}

	/**
	 * Set the app_perfil.
	 * 
	 * @param appPerfil
	 *            app_perfil
	 */
	public void setAppPerfil(Perfil appPerfil) {
		this.appPerfil = appPerfil;
	}

	/**
	 * Get the app_perfil.
	 * 
	 * @return app_perfil
	 */
	public Perfil getAppPerfil() {
		return this.appPerfil;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((funId == null) ? 0 : funId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Funcao other = (Funcao) obj;
		if (funId == null) {
			if (other.funId != null) {
				return false;
			}
		} else if (!funId.equals(other.funId)) {
			return false;
		}
		return true;
	}

}
