package geopixel.model.legacy.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of app_perfil.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Perfil implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** prf_id. */
	private Integer prfId;

	/** perfil. */
	private String perfil;

	/** The set of app_funcao. */
	private Set<Funcao> appFuncaoSet;

	/** The set of app_tema. */
	private Set<Tema> appTemaSet;

	/** The set of app_usarioxprefil. */
	private Set<Usarioxprefil> appUsarioxprefilSet;

	/**
	 * Constructor.
	 */
	public Perfil() {
		this.appFuncaoSet = new HashSet<Funcao>();
		this.appTemaSet = new HashSet<Tema>();
		this.appUsarioxprefilSet = new HashSet<Usarioxprefil>();
	}

	/**
	 * Set the prf_id.
	 * 
	 * @param prfId
	 *            prf_id
	 */
	public void setPrfId(Integer prfId) {
		this.prfId = prfId;
	}

	/**
	 * Get the prf_id.
	 * 
	 * @return prf_id
	 */
	public Integer getPrfId() {
		return this.prfId;
	}

	/**
	 * Set the perfil.
	 * 
	 * @param perfil
	 *            perfil
	 */
	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	/**
	 * Get the perfil.
	 * 
	 * @return perfil
	 */
	public String getPerfil() {
		return this.perfil;
	}

	/**
	 * Set the set of the app_funcao.
	 * 
	 * @param appFuncaoSet
	 *            The set of app_funcao
	 */
	public void setAppFuncaoSet(Set<Funcao> appFuncaoSet) {
		this.appFuncaoSet = appFuncaoSet;
	}

	/**
	 * Add the app_funcao.
	 * 
	 * @param appFuncao
	 *            app_funcao
	 */
	public void addAppFuncao(Funcao appFuncao) {
		this.appFuncaoSet.add(appFuncao);
	}

	/**
	 * Get the set of the app_funcao.
	 * 
	 * @return The set of app_funcao
	 */
	public Set<Funcao> getAppFuncaoSet() {
		return this.appFuncaoSet;
	}

	/**
	 * Set the set of the app_tema.
	 * 
	 * @param appTemaSet
	 *            The set of app_tema
	 */
	public void setAppTemaSet(Set<Tema> appTemaSet) {
		this.appTemaSet = appTemaSet;
	}

	/**
	 * Add the app_tema.
	 * 
	 * @param appTema
	 *            app_tema
	 */
	public void addAppTema(Tema appTema) {
		this.appTemaSet.add(appTema);
	}

	/**
	 * Get the set of the app_tema.
	 * 
	 * @return The set of app_tema
	 */
	public Set<Tema> getAppTemaSet() {
		return this.appTemaSet;
	}

	/**
	 * Set the set of the app_usarioxprefil.
	 * 
	 * @param appUsarioxprefilSet
	 *            The set of app_usarioxprefil
	 */
	public void setAppUsarioxprefilSet(Set<Usarioxprefil> appUsarioxprefilSet) {
		this.appUsarioxprefilSet = appUsarioxprefilSet;
	}

	/**
	 * Add the app_usarioxprefil.
	 * 
	 * @param appUsarioxprefil
	 *            app_usarioxprefil
	 */
	public void addAppUsarioxprefil(Usarioxprefil appUsarioxprefil) {
		this.appUsarioxprefilSet.add(appUsarioxprefil);
	}

	/**
	 * Get the set of the app_usarioxprefil.
	 * 
	 * @return The set of app_usarioxprefil
	 */
	public Set<Usarioxprefil> getAppUsarioxprefilSet() {
		return this.appUsarioxprefilSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prfId == null) ? 0 : prfId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Perfil other = (Perfil) obj;
		if (prfId == null) {
			if (other.prfId != null) {
				return false;
			}
		} else if (!prfId.equals(other.prfId)) {
			return false;
		}
		return true;
	}

}
