package geopixel.model.legacy.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of app_tema.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tema implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** tma_id. */
	private Integer tmaId;

	/** nome_tema. */
	private String nomeTema;

	/** titulo_tema. */
	private String tituloTema;

	/** descricao. */
	private String descricao;

	/** app_perfil. */
	private Perfil Perfil;

	/** app_camada. */
	private Camada Camada;

	/** The set of app_permissao. */
	private Set<Permissao> PermissaoSet;

	/**
	 * Constructor.
	 */
	public Tema() {
		this.PermissaoSet = new HashSet<Permissao>();
	}

	/**
	 * Set the tma_id.
	 * 
	 * @param tmaId
	 *            tma_id
	 */
	public void setTmaId(Integer tmaId) {
		this.tmaId = tmaId;
	}

	/**
	 * Get the tma_id.
	 * 
	 * @return tma_id
	 */
	public Integer getTmaId() {
		return this.tmaId;
	}

	/**
	 * Set the nome_tema.
	 * 
	 * @param nomeTema
	 *            nome_tema
	 */
	public void setNomeTema(String nomeTema) {
		this.nomeTema = nomeTema;
	}

	/**
	 * Get the nome_tema.
	 * 
	 * @return nome_tema
	 */
	public String getNomeTema() {
		return this.nomeTema;
	}

	/**
	 * Set the titulo_tema.
	 * 
	 * @param tituloTema
	 *            titulo_tema
	 */
	public void setTituloTema(String tituloTema) {
		this.tituloTema = tituloTema;
	}

	/**
	 * Get the titulo_tema.
	 * 
	 * @return titulo_tema
	 */
	public String getTituloTema() {
		return this.tituloTema;
	}

	/**
	 * Set the descricao.
	 * 
	 * @param descricao
	 *            descricao
	 */
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	/**
	 * Get the descricao.
	 * 
	 * @return descricao
	 */
	public String getDescricao() {
		return this.descricao;
	}

	/**
	 * Set the perfil.
	 * 
	 * @param appPerfil
	 *            app_perfil
	 */
	public void setPerfil(Perfil perfil) {
		this.Perfil = perfil;
	}

	/**
	 * Get the app_perfil.
	 * 
	 * @return app_perfil
	 */
	public Perfil getPerfil() {
		return this.Perfil;
	}

	/**
	 * Set the app_camada.
	 * 
	 * @param appCamada
	 *            app_camada
	 */
	public void setCamada(Camada camada) {
		this.Camada = camada;
	}

	/**
	 * Get the app_camada.
	 * 
	 * @return app_camada
	 */
	public Camada getCamada() {
		return this.Camada;
	}

	/**
	 * Set the set of the app_permissao.
	 * 
	 * @param appPermissaoSet
	 *            The set of app_permissao
	 */
	public void setPermissaoSet(Set<Permissao> appPermissaoSet) {
		this.PermissaoSet = appPermissaoSet;
	}

	/**
	 * Add the app_permissao.
	 * 
	 * @param appPermissao
	 *            app_permissao
	 */
	public void addPermissao(Permissao permissao) {
		this.PermissaoSet.add(permissao);
	}

	/**
	 * Get the set of the app_permissao.
	 * 
	 * @return The set of app_permissao
	 */
	public Set<Permissao> getPermissaoSet() {
		return this.PermissaoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((tmaId == null) ? 0 : tmaId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Tema other = (Tema) obj;
		if (tmaId == null) {
			if (other.tmaId != null) {
				return false;
			}
		} else if (!tmaId.equals(other.tmaId)) {
			return false;
		}
		return true;
	}

}
