package geopixel.model.legacy.dto;

import java.io.Serializable;

/**
 * Model class of app_usarioxprefil.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Usarioxprefil implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** app_perfil. */
	private Perfil appPerfil;

	/** app_usuario. */
	private Usuario appUsuario;

	/**
	 * Constructor.
	 */
	public Usarioxprefil() {
	}

	/**
	 * Set the app_perfil.
	 * 
	 * @param appPerfil
	 *            app_perfil
	 */
	public void setAppPerfil(Perfil appPerfil) {
		this.appPerfil = appPerfil;
	}

	/**
	 * Get the app_perfil.
	 * 
	 * @return app_perfil
	 */
	public Perfil getAppPerfil() {
		return this.appPerfil;
	}

	/**
	 * Set the app_usuario.
	 * 
	 * @param appUsuario
	 *            app_usuario
	 */
	public void setAppUsuario(Usuario appUsuario) {
		this.appUsuario = appUsuario;
	}

	/**
	 * Get the app_usuario.
	 * 
	 * @return app_usuario
	 */
	public Usuario getAppUsuario() {
		return this.appUsuario;
	}


}
