package geopixel.model.legacy.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of app_usuario.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Usuario implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** usr_id. */
	private Integer usrId;

	/** nome. */
	private String nome;

	/** cpf. */
	private String cpf;

	/** email. */
	private String email;

	/** telefone1. */
	private String telefone1;

	/** telefone2. */
	private String telefone2;

	/** The set of app_acesso. */
	private Set<Acesso> appAcessoSet;

	/** The set of app_endereco. */
	private Set<Endereco> appEnderecoSet;

	/** The set of app_usarioxprefil. */
	private Set<Usarioxprefil> appUsarioxprefilSet;

	/**
	 * Constructor.
	 */
	public Usuario() {
		this.appAcessoSet = new HashSet<Acesso>();
		this.appEnderecoSet = new HashSet<Endereco>();
		this.appUsarioxprefilSet = new HashSet<Usarioxprefil>();
	}

	/**
	 * Set the usr_id.
	 * 
	 * @param usrId
	 *            usr_id
	 */
	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	/**
	 * Get the usr_id.
	 * 
	 * @return usr_id
	 */
	public Integer getUsrId() {
		return this.usrId;
	}

	/**
	 * Set the nome.
	 * 
	 * @param nome
	 *            nome
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * Get the nome.
	 * 
	 * @return nome
	 */
	public String getNome() {
		return this.nome;
	}

	/**
	 * Set the cpf.
	 * 
	 * @param cpf
	 *            cpf
	 */
	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	/**
	 * Get the cpf.
	 * 
	 * @return cpf
	 */
	public String getCpf() {
		return this.cpf;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the telefone1.
	 * 
	 * @param telefone1
	 *            telefone1
	 */
	public void setTelefone1(String telefone1) {
		this.telefone1 = telefone1;
	}

	/**
	 * Get the telefone1.
	 * 
	 * @return telefone1
	 */
	public String getTelefone1() {
		return this.telefone1;
	}

	/**
	 * Set the telefone2.
	 * 
	 * @param telefone2
	 *            telefone2
	 */
	public void setTelefone2(String telefone2) {
		this.telefone2 = telefone2;
	}

	/**
	 * Get the telefone2.
	 * 
	 * @return telefone2
	 */
	public String getTelefone2() {
		return this.telefone2;
	}

	/**
	 * Set the set of the app_acesso.
	 * 
	 * @param appAcessoSet
	 *            The set of app_acesso
	 */
	public void setAppAcessoSet(Set<Acesso> appAcessoSet) {
		this.appAcessoSet = appAcessoSet;
	}

	/**
	 * Add the app_acesso.
	 * 
	 * @param appAcesso
	 *            app_acesso
	 */
	public void addAppAcesso(Acesso appAcesso) {
		this.appAcessoSet.add(appAcesso);
	}

	/**
	 * Get the set of the app_acesso.
	 * 
	 * @return The set of app_acesso
	 */
	public Set<Acesso> getAppAcessoSet() {
		return this.appAcessoSet;
	}

	/**
	 * Set the set of the app_endereco.
	 * 
	 * @param appEnderecoSet
	 *            The set of app_endereco
	 */
	public void setAppEnderecoSet(Set<Endereco> appEnderecoSet) {
		this.appEnderecoSet = appEnderecoSet;
	}

	/**
	 * Add the app_endereco.
	 * 
	 * @param appEndereco
	 *            app_endereco
	 */
	public void addAppEndereco(Endereco appEndereco) {
		this.appEnderecoSet.add(appEndereco);
	}

	/**
	 * Get the set of the app_endereco.
	 * 
	 * @return The set of app_endereco
	 */
	public Set<Endereco> getAppEnderecoSet() {
		return this.appEnderecoSet;
	}

	/**
	 * Set the set of the app_usarioxprefil.
	 * 
	 * @param appUsarioxprefilSet
	 *            The set of app_usarioxprefil
	 */
	public void setAppUsarioxprefilSet(Set<Usarioxprefil> appUsarioxprefilSet) {
		this.appUsarioxprefilSet = appUsarioxprefilSet;
	}

	/**
	 * Add the app_usarioxprefil.
	 * 
	 * @param appUsarioxprefil
	 *            app_usarioxprefil
	 */
	public void addAppUsarioxprefil(Usarioxprefil appUsarioxprefil) {
		this.appUsarioxprefilSet.add(appUsarioxprefil);
	}

	/**
	 * Get the set of the app_usarioxprefil.
	 * 
	 * @return The set of app_usarioxprefil
	 */
	public Set<Usarioxprefil> getAppUsarioxprefilSet() {
		return this.appUsarioxprefilSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((usrId == null) ? 0 : usrId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Usuario other = (Usuario) obj;
		if (usrId == null) {
			if (other.usrId != null) {
				return false;
			}
		} else if (!usrId.equals(other.usrId)) {
			return false;
		}
		return true;
	}

}
